name: "Set useful environment variables (IMAGE_TAG and CONTAINER_REPO)"
description: "IMAGE_TAG will be latest if current branch is main. Otherwise it will be the name of the branch (with '/' replaced by '-') or the tag.
CONTAINER_REPO will be as env.registry/env.CONTAINER_IMAGE"

runs:
  using: "composite"
  steps:
    - name: Set CONTAINER_REPO
      shell: bash
      run: |
        if [ -z "${{ env.REGISTRY }}" || -z "${{ env.CONTAINER_IMAGE }}" ]; then
          echo 'None of env.REGISTRY ("${{ env.REGISTRY }}") and env.CONTAINER_IMAGE ("${{ env.CONTAINER_IMAGE }}") should be empty! Set them before calling this action'

          exit 1
        fi

        echo CONTAINER_REPO="${{ env.REGISTRY }}/${{ env.CONTAINER_IMAGE }}" >> $GITHUB_ENV
    - name: Set IMAGE_TAG
      shell: bash
      run: |
        tag=${{ github.ref }}

        if [ ${tag} == 'refs/heads/main' ]; then
          tag='latest'
        else
          # Remove refs/*/.
          tag=${tag#refs/*/}
          # Replace / by - to avoid docker push crying.
          tag=${tag/\//-}
        fi

        echo IMAGE_TAG=${tag} >> $GITHUB_ENV
