name: Inspektor Gadget Cleanup
on: delete
env:
  GO_VERSION: 1.21.3
  REGISTRY: ghcr.io
  CONTAINER_REPO: ${{ github.repository }}

permissions: read-all

jobs:
  delete:
    # we don't want to mess up with forks for now
    if: github.repository == 'inspektor-gadget/inspektor-gadget'
    name: Branch delete
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
      id: go
    - name: Set container repository and determine image tag
      id: set-repo-determine-image-tag
      uses: ./.github/actions/set-container-repo-and-determine-image-tag
      with:
        registry: ${{ env.REGISTRY }}
        container-image: ${{ env.CONTAINER_REPO }}
    - name: Cleanup citest- tags
      run: |
        cd tools/packagescleanup
        go build .
        ./packagescleanup ${{ github.repository_owner }} ${{ steps.set-repo-determine-image-tag.outputs.image-tag }}
